baseURL = 'https://niuniu741.github.io/success-site/'
languageCode = 'en-us'
publishDir = "docs"
title = '直击财经'
theme = 'ananke'
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true